### ISSUE TITLE
NullPointer exception in history component

### ISSUE THREAD

**Issue by saviola777** [NanoDefiner/NanoDefiner#5]
```
java.util.NoSuchElementException: null
        at java.util.LinkedList.getLast(LinkedList.java:257)
        at eu.nanodefine.etool.controller.helper.history.History.getCurrent(History.java:121)
        at eu.nanodefine.etool.controller.advice.DefaultModelAttributesAdvice.breadcrumbs(DefaultModelAttributesAdvice.java:116)
```
When the e-tool was left in a logged-in state and the application is re-started, this error happens on the next visit. The error should be fixed or caught.

**Comment by saviola777** [comment]
Caused by errors parsing URLs that contained two slashes after the context path. Fixed in e13c529.
